#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : nosync
Version  : 1.0
Release  : 3
URL      : https://github.com/kjn/nosync/archive/1.0.tar.gz
Source0  : https://github.com/kjn/nosync/archive/1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: nosync-lib
Patch1: cflags.patch
Patch2: as-needed-fix.patch

%description
nosync
======
nosync is a small preload library that can be used to disable
synchronization of file's content with storage devices on GNU/Linux.
It works by overriding implementations of certain standard functions
like `fsync` or `open`.

%package lib
Summary: lib components for the nosync package.
Group: Libraries

%description lib
lib components for the nosync package.


%prep
%setup -q -n nosync-1.0
%patch1 -p1
%patch2 -p1

%build
make V=1  %{?_smp_mflags}

%install
rm -rf %{buildroot}
%make_install libdir=%{buildroot}/usr/lib64

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/nosync/nosync.so
